SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT U.user_id) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.user_id = S.user_id
WHERE gender IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;