-- 코드를 입력하세요
SELECT user_id, nickname, SUM(PRICE) AS TOTAL_PRICE
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B
ON user_id = WRITER_ID
WHERE status='DONE'
GROUP BY user_id
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_PRICE;